module Constantable
	# ACRONYMNS = %w( !!!! 02 10Q AFC LOL OMG )

	ACRONYMNS = { "02" => "Your two cents",
								"10Q" => "Thank you",
								"1174" => "Nude club",
								"121" => "One to one",
								"1337" => "Elite",
								"14" => "the fourteen words",
								"143" => "I love you",
								"1432" => "I Love You Too",
								"14AA41" => "One for All and All for One",
								"182" => "I hate you",
								"20" => "Location",
								"2BZ4UQT" => "Too Busy For You Cutey",
								"2DLOO" => "Toodle Oo",
								"2G2B4G" => "Too Good To Be Forgotten",
								"2G2BT" => "Too Good To Be True",
								"2moro" => "Tomorrow",
								"2nite" => "Tonight",
								"2QT" => "Too Cute",
								"2U2" => "To You Too",
								"303" => "Mom",
								"404" => "I haven't a clue",
								"411" => "Information",
								"420" => "Marijuana",
								"459" => "I love you",
								"4COL" => "For Crying Out Loud",
								"4EAE" => "For Ever And Ever",
								"AFC" => "Away From Computer",
								"LOL" => "Laughing Out Loud",
								"OMG" => "Oh My God",
								"ADR" => "Address",
								"AFAP" => "As Far As Possible" }
end